using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Player_Combat : MonoBehaviour 
{
    public Transform attackPoint;
    public float weaponRange = 1;
    public float knockbackForce = 50;
    public float knockbackTime = 0.15f;
    public float stunTime = 0.3f;
    public LayerMask enemyLayer;
    public int damage = 1;

    public Animator anim;

    public float cooldown = 10;
    private float timer;

    private void Update()
    {
        if(timer > 0)
        {
            timer -= Time.deltaTime;
        }

    }


    public void Attack()
    {

        if (timer <= 0)
        {
            anim.SetBool("IsAttacking", true);

            timer = cooldown;
        }
    }

    //public void DealDamage()
    //{
    //    Collider2D[] enemies = Physics2D.OverlapCircleAll(attackPoint.position, weaponRange, enemyLayer);

    //    if (enemies.Length > 0)
    //    {
    //        enemies[0].GetComponent<Knight>().ChangeHealth(-damage);
    //        //enemies[0].GetComponent<Enemy_Knockback>().Knockback(transform, knockbackForce, knockbackTime, stunTime);
    //    }
    //}
    public void DealDamage()
    {
        Collider2D[] enemies = Physics2D.OverlapCircleAll(attackPoint.position, weaponRange, enemyLayer);

        if (enemies.Length > 0)
        {
            // Try to get something that can take damage
            IDamagable damageable = enemies[0].GetComponent<IDamagable>();

            if (damageable != null)
            {
                damageable.Damage(damage);    // this will call Enemy.Damage(), which triggers the flash
            }
            else
            {
                Debug.LogWarning("Hit something on enemyLayer that doesn't implement IDamagable.", enemies[0]);
            }
        }
    }




    public void FinishAttacking()
    {

        anim.SetBool("IsAttacking", false);

    }

    private void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(attackPoint.position, weaponRange);
    }

}